### ISSUE TITLE
TODO: cogs/danbooru

### ISSUE THREAD

**Issue by fiffu** [fiffu/arisa2#2]
- [x] Figure out a nice way to deal with cog-level configs
- [x] Refactor the search pipeline
- [x] Main search function
- [x] Improve embed layout (include the pic's series/copyright)
- [x] Port over vetos on particular booru search queries
- [x] Add `!dan` command for "raw" image querying
- [ ] "Did you mean..." (probably for searches with 0 results)

**Comment by fiffu** [comment]
Last feature is kind of hard to do. 
One approach would be to try and fix common mistake patterns (like `firstname_lastname` when they should be `lastname_firstname`). This is probably be implemented.
Another approach would be popping off letters from the end and repeating a wildcard search with the shortened tag until it resolves into a valid tag, but that doesn't seem very useful or efficient.

**Comment by fiffu** [comment]
Merge #14 into todo issue
