### ISSUE TITLE
TODO: Evolving colour roles

### ISSUE THREAD

**Issue by fiffu** [fiffu/arisa2#3]
- [x] DB prep work
- [x] Externalize configs
- [x] Figure out how the "mutating" role should be managed (creation, precedence vs other roles etc)
- [x] Port over mutate and reroll methods
